# Generated by Django 4.0.4 on 2022-05-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=30)),
                ('periodo', models.IntegerField()),
                ('puesto', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universidad', models.CharField(max_length=40)),
                ('anio_inicio', models.IntegerField()),
                ('titulo', models.CharField(max_length=40)),
                ('finalizado', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=40)),
                ('nro_fuelo', models.IntegerField()),
                ('fecha', models.DateField()),
                ('notas', models.CharField(max_length=200)),
            ],
        ),
    ]
