# Generated by Django 4.0.4 on 2022-05-30 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_sab_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viajes',
            old_name='nro_fuelo',
            new_name='nro_vuelo',
        ),
    ]
